# Generated by Django 6.0.3 on 2026-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_created_at_document_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='teacher',
        ),
        migrations.AddField(
            model_name='document',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_documents', to='core.profile'),
        ),
    ]
