# Generated by Django 6.0.4 on 2026-04-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_document_teacher_document_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.class'),
        ),
    ]
